version: "3.8"
services:
  backend:
    image: "robenhoud/springboot-react-fullstack:5.10.2022.14.24.7"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev